openapi: 3.0.3
info:
  title: Smart Alarm API
  version: 1.0.0
  description: Документация backend API для умного будильника.
paths:
  /api/alarms/:
    get:
      operationId: alarms_list
      tags:
      - alarms
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alarm'
          description: ''
    post:
      operationId: alarms_create
      tags:
      - alarms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alarm'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Alarm'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Alarm'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alarm'
          description: ''
  /api/alarms/{id}/:
    get:
      operationId: alarms_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this alarm.
        required: true
      tags:
      - alarms
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alarm'
          description: ''
    put:
      operationId: alarms_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this alarm.
        required: true
      tags:
      - alarms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alarm'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Alarm'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Alarm'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alarm'
          description: ''
    patch:
      operationId: alarms_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this alarm.
        required: true
      tags:
      - alarms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAlarm'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAlarm'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAlarm'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alarm'
          description: ''
    delete:
      operationId: alarms_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this alarm.
        required: true
      tags:
      - alarms
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/health/:
    get:
      operationId: health_retrieve
      tags:
      - health
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: ''
  /api/profile/:
    get:
      operationId: profile_retrieve
      tags:
      - profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: profile_update
      tags:
      - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdate'
          description: ''
    patch:
      operationId: profile_partial_update
      tags:
      - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProfileUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProfileUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProfileUpdate'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdate'
          description: ''
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Alarm:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        time:
          type: string
          format: time
        label:
          type: string
          maxLength: 255
        is_active:
          type: boolean
        task_type:
          $ref: '#/components/schemas/TaskTypeEnum'
        difficulty:
          $ref: '#/components/schemas/DifficultyEnum'
        volume:
          type: integer
          maximum: 2147483647
          minimum: 0
        attempts:
          type: integer
          maximum: 2147483647
          minimum: 0
        repeat_days: {}
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - time
      - updated_at
    CustomTokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    DifficultyEnum:
      enum:
      - easy
      - medium
      - hard
      type: string
      description: |-
        * `easy` - Easy
        * `medium` - Medium
        * `hard` - Hard
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
        service:
          type: string
      required:
      - service
      - status
    PatchedAlarm:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        time:
          type: string
          format: time
        label:
          type: string
          maxLength: 255
        is_active:
          type: boolean
        task_type:
          $ref: '#/components/schemas/TaskTypeEnum'
        difficulty:
          $ref: '#/components/schemas/DifficultyEnum'
        volume:
          type: integer
          maximum: 2147483647
          minimum: 0
        attempts:
          type: integer
          maximum: 2147483647
          minimum: 0
        repeat_days: {}
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    PatchedProfileUpdate:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          nullable: true
          maxLength: 20
        avatar:
          type: string
    ProfileUpdate:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          nullable: true
          maxLength: 20
        avatar:
          type: string
      required:
      - username
    Register:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          nullable: true
          maxLength: 20
        avatar:
          type: string
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
      required:
      - confirm_password
      - id
      - password
      - username
    TaskTypeEnum:
      enum:
      - math
      - photo
      - logic
      - memory
      type: string
      description: |-
        * `math` - Math
        * `photo` - Photo
        * `logic` - Logic
        * `memory` - Memory
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        phone:
          type: string
          nullable: true
          maxLength: 20
        avatar:
          type: string
      required:
      - id
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
