# Generated by Django 4.2.29 on 2026-04-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="attempts",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="alarm",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alarm",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="repeat_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alarm",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("math", "Math"),
                    ("photo", "Photo"),
                    ("shake", "Shake"),
                    ("memory", "Memory"),
                ],
                default="math",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="volume",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
