# Generated by Django 5.2.1 on 2026-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0002_alarm_attempts_alarm_created_at_alarm_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("math", "Math"),
                    ("photo", "Photo"),
                    ("logic", "Logic"),
                    ("memory", "Memory"),
                ],
                default="math",
                max_length=20,
            ),
        ),
    ]
