# Generated by Django 5.2.1 on 2026-04-10 06:10

import apps.alarms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0003_alter_alarm_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="repeat_days",
            field=models.JSONField(
                blank=True, default=apps.alarms.models.default_repeat_days
            ),
        ),
    ]
